name: clw_env_py36_torch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.5.15=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - decorator=4.4.0=py36_1
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - ipython=7.7.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.3=py36_0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.16.4=py36h7e9f1db_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1c=h7b6447c_1
  - parso=0.5.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.1.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - scipy=1.3.0=py36h7c811a0_0
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.1=py36_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.1.0=py3.6_cuda10.0.130_cudnn7.5.1_0
  - pytorch-nightly=1.2.0.dev20190802=py3.6_cuda10.0.130_cudnn7.6.1_0
  - pip:
    - cycler==0.10.0
    - cython==0.29.13
    - editdistance==0.5.3
    - kiwisolver==1.1.0
    - matplotlib==3.1.1
    - pycocotools==2.0
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - pyyaml==5.1.2
    - rrpn==0.0.0
    - torch==1.2.0.dev20190802
    - yacs==0.1.6
prefix: /home/clwclw/anaconda3/envs/clw_env_py36_torch

